---
- name: Get IMDSv2 token
  uri:
    url: http://169.254.169.254/latest/api/token
    headers:
      X-aws-ec2-metadata-token-ttl-seconds: 21600
    method: PUT
    return_content: yes
  register: token

- name: Get instance ID
  uri:
    url: http://169.254.169.254/latest/meta-data/instance-id
    headers:
      X-aws-ec2-metadata-token: "{{ token.content }}"
    method: GET
    return_content: yes
  register: instance_id

- name: Deregister instance from ELB
  shell:
    cmd: >-
      aws elbv2 deregister-targets --region=eu-central-1
      --target-group-arn "{{ target_group_arn }}"
      --targets "Id={{ instance_id.content }}"

- name: Wait for target to become unused
  shell:
    cmd: >-
      aws elbv2 describe-target-health --region=eu-central-1
      --target-group-arn "{{ target_group_arn }}"
      --targets "Id={{ instance_id.content }}"
  register: health
  until: "( health.stdout | from_json ).TargetHealthDescriptions[0].TargetHealth.State == 'unused'"
  changed_when: false
  retries: 10
  delay: 10