---
- hosts: apps
  become: yes
  serial: 1

  vars:
    deploy_dir: /opt/app

  vars_files:
    - vars/target_group.yml

  tasks:
    - import_tasks: tasks/deregister.yml
    - import_tasks: tasks/git-commit.yml
    - import_tasks: tasks/deploy.yml
    - import_tasks: tasks/reload-service.yml
    - import_tasks: tasks/register.yml